### ISSUE TITLE
Questions about data formatting in this framework

### ISSUE THREAD

**Issue by StoneWU1992** [BoyangL1/Advanced_DeepIRL#1]
Dear author，
Thanks for a nice framework!
I'd like to ask if your raw trajectory data using this framework exists as a point record or is it recorded as a line?

**Comment by BoyangL1** [comment]
Our original data consists of point data from mobile phone signaling. We perform road network matching on it and use geopandas to convert it into the linestring format, saving it as a traj.shp file.

**Comment by StoneWU1992** [comment]
Thank you very much for your patience in replying and have a happy new year.
